src/mobu/config.py
src/mobu/monkey.py

Add an alert method which will call the ALERT_HOOK URL and post the
exception message to it along with the username that caused it and
the timestamp of the error.

[DM-25835] Add alert hook and call it on exception

---

.github/dependabot.yml
.github/workflows/ci.yaml
pyproject.toml
requirements/dev.txt
requirements/main.in
requirements/main.txt
setup.cfg
src/mobu/__init__.py

- Add dependabot configuration
- Require Python 3.8 or later and drop compatibility with Python 3.7
- Use a matrix for Python versions in CI and test 3.8 and 3.9
- Update versions of GitHub Actions dependencies
- Regenerate and update dependencies

[DM-28993] Update Python version and dependencies

---

src/mobu/notebookrunner.py

Add a way to have some time before the notebook runner starts
trying to run notebooks, so that we might not get that 405.

[DM-29112] Add a settle timer

---

src/mobu/jupyterclient.py

Before I would wait since it seemed like we would get a bunch of 200
status codes.  But if the first status code is a 500, apparently we
swallow it and keep waiting.  The next request gets a 200, even though
it isn't waiting at all for progress.  This is why it takes a whole
timeout of running through that loop, but really we should signal the
first error we see.  This won't fix anything, I don't think, but it
should reduce some noise and change some timings.

[DM-29321] Bail out on bad progress URL status codes

---

src/mobu/jupyterclient.py

Maybe the kernel thing broken when we got rid of system python
kernel?  I don't see it in the list anymore.

[DM-29321] Switch kernel name

---

requirements/dev.in
requirements/dev.txt
src/mobu/config.py
src/mobu/handlers/external/user.py
src/mobu/monkeybusinessfactory.py
src/mobu/user.py
tests/user_test.py

Allow a Gafaelfawr admin token to be passed in via an environment
variable as configuration.  If that is set, get a user token for
the target user via a Gafaelfawr admin API call.  If not, fall back
on the old JWT construction logic.

[DM-28120] Support Gafaelfawr 2.0

---

src/mobu/jupyterclient.py
src/mobu/notebookrunner.py

Okay, so after a lot of investigation, I think the issue is a timing issue.  We were slower and I think waited longer on the deletes for nublado1 than nublado2.  Either way, we were able to delete the lab and recreate it after checking against the success count, and I think this quick re-making of the lab caused the issue.  While we weren't ready or after the lab had been deleted, we tried to make requests to make a kernel, which the code shouldn't have allowed, but perhaps there is a state during cleanup where the URL isn't a 404 yet, but isn't valid either.
Either way, I'm deleting the lab at the beginning of each cycle, right after the hub.  I've also gotten really explicit about the URL flow, which makes it a little more brittle, but also a little more clear what is happening.  This …

[DM-29799] Fix robo-simon startup timing issue

---

src/mobu/handlers/external.py
src/monkeyflocker/client.py
tests/business/jupyterloginloop_test.py
tests/business/jupyterpythonloop_test.py
tests/handlers/flock_test.py

The client uploads a complete configuration, not a partial one
that's modified, so PUT seems like a more appropriate verb.

[DM-31083] Use PUT instead of POST for creating flocks

---

src/mobu/business/base.py
src/mobu/business/jupyterjitterloginloop.py
src/mobu/business/jupyterloginloop.py
src/mobu/business/jupyterpythonloop.py
src/mobu/business/notebookrunner.py
src/mobu/business/querymonkey.py
src/mobu/dependencies/manager.py
src/mobu/jupyterclient.py
src/mobu/models/business.py
src/mobu/monkey.py
tests/autostart_test.py
tests/business/jupyterloginloop_test.py
tests/business/jupyterpythonloop_test.py
tests/conftest.py
tests/handlers/flock_test.py
tests/monkeyflocker_test.py
tests/support/jupyter.py

- Add proper shutdown support for monkeys using a queue to coordinate
- Refactor the business classes more to reuse more code and better document overrides
- Make shutting down the lab between notebook executions optional
- Use max_interations for NotebookRunner as well, instead of its own config variable
- Lift more infrastructure into the base business class
- Reauthenticate to the lab before deleting a session
- Poll the hub URL instead of the pending spawn URL to see if the lab is up since the latter sometimes 503s
- Make the default JupyterPythonLoop code produce cleaner logs
- Fix desynchronization of the web socket that caused the results of code execution to be lost
- Remove the periodic hub reauth code (should now be unnecessary)
- Wait for the lab to shut down after deletion
- …

[DM-31201] Clean shutdown and other fixes

---

src/mobu/business/jupyterpythonloop.py
src/mobu/business/notebookrunner.py
src/mobu/exceptions.py
src/mobu/jupyterclient.py
src/mobu/models/business.py
src/mobu/models/timings.py
src/mobu/monkey.py
src/mobu/slack.py
src/mobu/timings.py
tests/business/jupyterloginloop_test.py
tests/business/jupyterpythonloop_test.py
tests/business/notebookrunner_test.py
tests/notebooks/data-file
tests/notebooks/exception.ipynb
tests/notebooks/test-notebook.ipynb
tests/support/jupyter.py
tests/timings_test.py

- Add support for setting the working directory when running a notebook
- Add support for getting the node on which a notebook is running and reporting it in alerts
- Catch and translate the poor aiohttp exception from a closed WebSocket
- Improve the way we determine what notebooks to run
- Report the cell of the notebook that was being executed when an alert fires
- Simplify the timing data that's gathered and reported
- Add divider after unknown exception reports to make them easier to read

[DM-31406] Prepare mobu for running the tutorial notebook

---

src/mobu/business/jupyterloginloop.py
src/mobu/business/jupyterpythonloop.py
src/mobu/business/notebookrunner.py
src/mobu/cachemachine.py
src/mobu/exceptions.py
src/mobu/jupyterclient.py
src/mobu/models/business.py
src/mobu/models/jupyter.py
tests/autostart_test.py
tests/business/jupyterloginloop_test.py
tests/business/jupyterpythonloop_test.py
tests/business/notebookrunner_test.py
tests/conftest.py
tests/support/cachemachine.py

Rather than configuring mobu with the raw values to post to the
spawner form, support asking cachemachine for an image satisfying
a particular quality (recommended and latest weekly being the main
supported ones right now), and then determine the correct thing to
send to the spawner page from that.
Use this infrastructure to record the image name in error reports
and in metadata about a running monkey business.

[DM-31490] Overhaul how Jupyter images are selected

---

src/mobu/exceptions.py
tests/business/jupyterpythonloop_test.py
tests/support/jupyter.py

Slack has a limit on block sizes of 3000 characters, but sometimes
errors can be longer than that.  Trim errors and code from the top
(since the bottom is usually more interesting) to get it below
Slack's limit so that we don't have missing alerts.

[DM-31581] Trim errors and code to 3000 characters

---

src/mobu/jupyterclient.py

The regular user token cannot access cachemachine.  Use the token
that mints other user tokens instead, since we can grant it access.

[DM-31490] Use correct token for cachemachine queries

---

src/mobu/jupyterclient.py

Since the JupyterLab interface doesn't impose a message size limit, it makes sense to treat the notebooks run in CI the same way.  We may want to do a sweep occasionally to see how big the messages are, but I'm not sure it's the right thing to fail on them.

DM-32329: Allow web socket messages of any size

---

src/mobu/templates/tapqueryrunner/cone-object.sql
src/mobu/templates/tapqueryrunner/cone-photometry.sql
src/mobu/templates/tapqueryrunner/cone-position.sql
src/mobu/templates/tapqueryrunner/histogram-flux.sql
src/mobu/templates/tapqueryrunner/histogram-magnitude.sql
src/mobu/templates/tapqueryrunner/neighbor-near.sql
src/mobu/templates/tapqueryrunner/object-one.sql
src/mobu/templates/tapqueryrunner/object-photometry.sql
src/mobu/templates/tapqueryrunner/object-reference.sql
src/mobu/templates/tapqueryrunner/object-several.sql
src/mobu/templates/tapqueryrunner/polygon-object.sql
src/mobu/templates/tapqueryrunner/polygon-position.sql
src/mobu/templates/tapqueryrunner/scan-flux.sql
src/mobu/templates/tapqueryrunner/scan-magnitude.sql
src/mobu/templates/tapqueryrunner/scan-top.sql

Add a static "monkey" string to each SELECT clause in the TAP
queries (previously, the histograms were missing one).  Add a
second static string specifying the query template to each query.
This makes it easier to generate statistics on the qserv side.

[DM-35246] Add more query annotations to TAP queries

---

pyproject.toml
src/mobu/business/base.py
src/mobu/business/jupyterloginloop.py
src/mobu/business/jupyterpythonloop.py
src/mobu/business/notebookrunner.py
src/mobu/business/tapqueryrunner.py
src/mobu/cachemachine.py
src/mobu/config.py
src/mobu/dependencies/manager.py
src/mobu/exceptions.py
src/mobu/jupyterclient.py
src/mobu/models/business.py
src/mobu/models/flock.py
src/mobu/models/jupyter.py
src/mobu/models/timings.py
src/mobu/models/user.py
src/mobu/monkey.py
src/mobu/timings.py
src/mobu/util.py
src/monkeyflocker/cli.py
src/monkeyflocker/client.py
tests/autostart_test.py
tests/business/notebookrunner_test.py
tests/conftest.py
tests/handlers/flock_test.py
tests/monkeyflocker_test.py
tests/support/jupyter.py
tests/support/util.py
tests/timings_test.py

Use the current mypy configuration, and work around typing limitations in GitPython. Follow the PEP-585 recommendations for type imports, use lowercase types where possible, use the new union syntax where appropriate, and use Self where appropriate.

DM-38339: Update mypy configuration and type annotations

---

src/mobu/business/base.py
src/mobu/business/jupyterloginloop.py
src/mobu/business/tapqueryrunner.py
src/mobu/cachemachine.py
src/mobu/config.py
src/mobu/constants.py
src/mobu/flock.py
src/mobu/handlers/external.py
src/mobu/jupyterclient.py
src/mobu/main.py
src/mobu/models/user.py
src/mobu/status.py
src/mobu/timings.py
tests/autostart_test.py
tests/business/jupyterloginloop_test.py
tests/conftest.py
tests/monkeyflocker_test.py
tests/support/gafaelfawr.py
tests/support/jupyter.py
tests/support/monkeyflocker.py
tests/timings_test.py

- Use `current_datetime` and `format_datetime_for_logging` from Safir
- Convert the configuration class to `Settings` and do more validation of input
- Update the logging configuration to use enums and also configure Uvicorn logging
- Use `spawn_uvicorn` to start a process for monkeyflocker testing

DM-38339: Update to latest Safir, use Settings for config

---

tests/autostart_test.py
tests/business/jupyterloginloop_test.py
tests/business/jupyterpythonloop_test.py
tests/business/notebookrunner_test.py
tests/business/tapqueryrunner_test.py
tests/conftest.py
tests/handlers/flock_test.py
tests/user_test.py

Following the use of relative imports for the main mobu code, also use relative imports for tests for the test support modules.

DM-38339: Use relative imports for test modules

---

src/mobu/business/base.py
src/mobu/cachemachine.py
src/mobu/handlers/external.py
src/mobu/handlers/internal.py
src/mobu/jupyterclient.py
src/mobu/timings.py
src/mobu/util.py

Take advantage of Sphinx's new support for type annotations and remove type information from docstrings except for the return value, which now doesn't need a variable name.
Remove docstrings from routes, and remove __all__ in the handler module since we won't generate documentation for that (even if we get around to generating documentation).

DM-38339: Remove types from docstrings

---

src/mobu/business/notebookrunner.py
src/mobu/exceptions.py
tests/business/notebookrunner_test.py

The notebook was included in the main part of the Slack message when reporting a code execution failure, but not when reporting other problems such as web socket issues. Add the notebook to the cell in the common fields added from annotations so that it will always be present even for exceptions that don't add it to the main Slack message.

DM-38339: Add notebook to Slack error reports

---

src/mobu/models/business/jupyterloginloop.py
src/mobu/services/business/jupyterloginloop.py
tests/business/jupyterloginloop_test.py
tests/business/jupyterpythonloop_test.py
tests/business/notebookrunner_test.py

This defaulted to 0, we set it to 0 everywhere in the test suite, and we haven't set it to anything other than 0 in Phalanx, so it doesn't appear to be needed. Remove it and simplify the configuration.

DM-38339: Remove lab_settle_time configuration

---

src/mobu/exceptions.py
src/mobu/services/business/base.py
src/mobu/services/business/tapqueryrunner.py
tests/business/tapqueryrunner_test.py

TAPQueryRunner previously was creating a TAP client in __init__, which meant that failure to reach the TAP server caused the entire flock creation to fail. Move creation of the client to startup to correctly follow the Business API, and wrap it in a timer and better exception handling so that we get nice Slack reports.
A business wasn't counting failures during startup as a failed execution, which meant that monkeys that kept failing during startup would show as 100% successful in the summary. Increment the failure count if startup raises an exception to avoid this.

DM-38339: Handle failures during TAPQueryRunner setup

---

src/mobu/dependencies/context.py
src/mobu/factory.py
src/mobu/handlers/external.py
src/mobu/models/business/base.py
src/mobu/models/solitary.py
src/mobu/services/business/base.py
src/mobu/services/monkey.py
src/mobu/services/solitary.py
tests/handlers/solitary_test.py

Sometimes rather than running a business continuously in the background and reporting the results to Slack, we want to run that same business once to completion and then report the results, particularly whether it succeeded or failed. We'll use this later to do things like check whether a new deployment of Phalanx is functional.
Add support for this to mobu via a POST /run route and a new concept called a Solitary. This is parallel to a Flock, except rather than managing a possibly large number of monkeys doing business in the background, it manages a single monkey doing its business in the foreground until it finishes.

DM-38339: Add support for running a business once

---

CHANGELOG.md
src/mobu/services/business/nublado.py

Stripping before splitting means that we raise a random ValueError if one of the environment variables was missing. More generally, we got several exceptions that I think may be due to the lab getting shut down while we were asking it questions. Be more robust when parsing the response and treat any unrecognized response as providing no data.

DM-38425: Be more robust when getting the running image

---

changelog.d/20230504_132825_rra_DM_38425.md
src/mobu/models/business/nublado.py

In mobu 5.0.0, I had changed the default error_idle_time for those businesses that use Jupyter labs due to problems with recreating the lab after an error. This turned out to be a bug in the new lab controller which should now be fixed, so revert this back to 60 seconds.

DM-38425: Revert error_idle_time change from 5.0.0

---

changelog.d/20230504_142201_rra_DM_38425.md
src/mobu/services/business/nublado.py

When determining what image is running for error reporting purposes in businesses based on Nublado, ask for JUPYTER_IMAGE_SPEC rather than JUPYTER_IMAGE. The latter is deprecated.

DM-38425: Use JUPYTER_IMAGE_SPEC, not JUPYTER_IMAGE

---

src/mobu/services/business/nublado.py

In Nublado-based business, we retrieve the image reference and description from environment variables during lab startup for error reporting. Also log those to the monkey log.

DM-38425: Log image reference and description in monkey

---

changelog.d/20230504_155544_rra.md
src/mobu/exceptions.py
tests/business/jupyterpythonloop_test.py
tests/business/notebookrunner_test.py

In Google Kubernetes Engine, nodes are often longer than the useful width of a field. Cell is also often longer than the width of a field when there is notebook information and a UUID available. Format both as full Slack Block Kit blocks instead of fields so that they get the full width of the message and don't mess up the column formatting.

DM-38425: Format node and cell as blocks

---

.pre-commit-config.yaml
Makefile
changelog.d/20230510_082737_rra_DM_38425.md
changelog.d/20230510_083114_rra_DM_38425.md
pyproject.toml
src/mobu/config.py
src/mobu/exceptions.py
src/mobu/handlers/external.py
src/mobu/handlers/internal.py
src/mobu/main.py
src/mobu/services/business/base.py
src/mobu/services/business/nublado.py
src/mobu/services/flock.py
src/mobu/services/manager.py
src/monkeyflocker/cli.py

- Enable blacken-docs and pydocstyle
- Allow configuration of the path prefix using the standard Safir environment variable
- Enable Slack reporting of uncaught exceptions from the route handlers
- Use the Safir ClientRequestError framework
- Fix the Makefile run target

DM-38425: Adopt current Safir conventions

---

src/mobu/constants.py
src/mobu/exceptions.py
src/mobu/factory.py
src/mobu/models/user.py
src/mobu/services/flock.py
src/mobu/services/manager.py
src/mobu/services/solitary.py
src/mobu/storage/gafaelfawr.py
tests/storage/gafaelfawr_test.py
tests/support/gafaelfawr.py

Rather than embedding the Gafaelfawr client in the AuthenticatedUser model, separate out a Gafaelfawr storage client. Use copies of the Gafaelfawr models rather than sending and receiving raw JSON. These can be replaced with the real Gafaelfawr models once those are available from PyPI.
Take advantage of this to use Pydantic for the parsing and capture Gafaelfawr parsing errors in a Slack-reportable exception.

DM-38425: Split out Gafaelfawr storage layer and use models

---

src/mobu/storage/jupyter.py
tests/support/jupyter.py

Previously, the Jupyter client was requesting the login page with redirects disabled, which does not appear to be enough to force an authentication refresh and allow us to make API calls. Try fetching the hub home page instead with redirects enabled.

DM-38425: Change how we force a refresh of JupyterHub auth

---

changelog.d/20230511_132330_rra_DM_38425.md
src/mobu/models/business/nublado.py
src/mobu/storage/jupyter.py
tests/business/jupyterpythonloop_test.py

Add a debug flag to the configuration for any Nublado-based business that allows turning on lab debugging by passing the enable_debug flag through the JupyterHub spawner form.

DM-38425: Allow enabling of lab debugging

---

src/mobu/constants.py
src/mobu/storage/jupyter.py
tests/conftest.py

Add a constant so that we can configure a WebSocket message size limit in the future, but remove the default limit to match the previous aiohttp behavior. We have some notebooks that return images as part of cell execution and they exceeded the default 1MB limit on WebSocket message sizes.

DM-38425: Remove WebSocket message size limit

---

src/mobu/handlers/external.py

Starlette FileResponse no longer works to return monkey logs because it now commits to a Content-Length when starting to stream the file but doesn't stop sending data at that cutoff, so it sends more data than Content-Length since the log file is changing, and that in turn causes an HTTP protocol failure that prevents Chrome (at least) from successfully downloading the file.
Instead, simulate that with StreamResponse while setting a Content-Disposition header.

DM-38425: Stream monkey logs instead of using FileResponse

---

src/mobu/constants.py
src/mobu/storage/jupyter.py
tests/conftest.py

10 seconds, the default, may be too fast for the kernel to start. Try 60 seconds. It looks like aiohttp was using 300 seconds, so we can go as high as that.

DM-38425: Increase the WebSocket open timeout

---

src/mobu/constants.py

This is aiohttp's default, so hopefully should be safe with the new httpx-based protocol as well. It seems better than not setting a limit at all, since notebooks that return truly huge results probably should not do so.

DM-38425: Set maximum WebSocket message size to 4MB

---

changelog.d/20230515_104223_rra_DM_38425.md
changelog.d/20230515_112657_rra_DM_38425.md
src/mobu/exceptions.py
src/mobu/services/flock.py
src/mobu/services/monkey.py
tests/business/jupyterpythonloop_test.py
tests/business/notebookrunner_test.py
tests/business/tapqueryrunner_test.py

When reporting business exceptions to Slack, include the monkey and, if relevant, the flock. Change the fields for reporting unexpected exceptions (ones that don't know how to format themselves for Slack) to use the same field names as supported exceptions.

DM-38425: Include the monkey and flock in Slack exceptions

---

changelog.d/20230522_093320_rra_DM_39325.md
src/mobu/constants.py
src/mobu/models/business/nublado.py
src/mobu/storage/jupyter.py

One of the tutorial notebooks returns messages larger than 4MB. Bump the default size to 10MB, which from some research appears to match the Tornado default limit, and make it configurable per business so that we can tweak it further if necessary.

DM-39325: Make max WebSocket message size configurable

---

changelog.d/20230522_120303_rra_DM_39325.md
src/mobu/config.py
src/mobu/exceptions.py
src/mobu/models/business/nublado.py
src/mobu/services/business/nublado.py
src/mobu/storage/cachemachine.py
src/mobu/storage/jupyter.py
tests/business/jupyterpythonloop_test.py

Allow use of cachemachine and the cachemachine image policy are now configurable in the business options rather than globally.
Restructure code and options to move more things out of the JupyterClient class into the business logic to allow JupyterClient to more easily be moved into Safir, including managing the cachemachine client construction.
Fix passing the maximum WebSocket size into JupyterClient, missed in the previous PR.
Ignore WebSocket messages of type `display_data`, since those are not interesting to us.

DM-39325: Move cachemachine configuration into business options

---

changelog.d/20230522_163207_rra_DM_39325.md
src/mobu/exceptions.py
tests/business/jupyterpythonloop_test.py

When reporting errors to Slack, mobu 5.0.0 mistakenly started stripping ANSI escape sequences from the code being executed, which should be safe since it comes from local notebooks or configuration, instead of the error output, which is where Jupyter labs like to add formatting. Strip ANSI escape sequences from the error output instead of the code.

DM-39325: Fix stripping of ANSI escapes in Slack messages

---

src/mobu/storage/jupyter.py

execute_result is another WebSocket message type that we don't care about. Move the ignore list to a class variable and comment it.

DM-39360: Also ignore execute_result messages

---

changelog.d/20230526_123621_rra_DM_39360.md
src/mobu/storage/jupyter.py

If there was a timeout while opening a WebSocket to the lab, mobu failed with an unbound variable exception. Add an assignment to fix that problem.

DM-39360: Fix timeout reporting opening WebSocket

---

changelog.d/20230531_121107_rra_DM_39360.md
src/mobu/models/business/nublado.py
src/mobu/services/business/nublado.py
src/mobu/storage/jupyter.py

Allow configuration of the timeout used when talking to JupyterHub and Jupyter labs, and increase the default to 60s since we're seeing a fair number of possibly spurious timeouts in production.

DM-39360: Make Jupyter client timeout configurable

---

src/mobu/storage/jupyter.py

Comm messages are a custom messaging protocol used by the lab to talk to extensions running in the browser. They should be ignored by mobu.

DM-39552: Ignore comm messages from the lab

---

changelog.d/20230605_092121_rra_DM_39552.md
src/mobu/storage/jupyter.py

The send to the WebSocket was mistakenly outside of the try/except block for catching WebSocket exceptions. Move it inside the block for improved error reporting.

DM-39552: Catch exceptions while sending to the WebSocket

---

requirements/dev.in
requirements/dev.txt

This module was never used (we use respx for testing instead).

DM-39552: Remove pytest-httpx dependency

---

.github/workflows/ci.yaml
.github/workflows/dependencies.yaml
.github/workflows/periodic.yaml

Adopt the new way of running neophile from GitHub Actions. Add a non-blocking test for whether dependencies are up-to-date, a periodic workflow to update pre-commit dependencies, and a periodic workflow to test with updated pinned dependencies.

DM-39627: Run neophile from GitHub Actions

---

.pre-commit-config.yaml
changelog.d/20230706_111300_rra_DM_39552.md
src/mobu/models/business/nublado.py
src/mobu/services/flock.py

Previously, to generate a flock summary, mobu first converted all information about the running monkeys to output data structures and then added up success and failure counts from those. Because of the huge amount of timing data that mobu gathers, this took long enough (and is not async, so it blocks everything else) that other in-progress calls timed out. It also meant that the summary end point appeared to hang.
Avoid this by reading the success and failure counts directly from the running monkey business, avoiding the need to dump and thus convert their data. This is a temporary fix until the way that timing data is stored can be overhauled.

DM-39552: Generate less data when summarizing flocks

---

.pre-commit-config.yaml
pyproject.toml
src/mobu/storage/jupyter.py

Use Ruff instead of Black to reformat code, although continue to use blacken-docs for documentation since Ruff does not yet have an equivalent. Merge Ruff exclusions with Nublado and drop settings no longer required with Pydantic v2.

DM-42182: Switch to Ruff for reformatting

---

tests/monkeyflocker_test.py

Don't catch exceptions in the Click CliRunner. Letting them go uncaught makes debugging a lot easier.

DM-42182: Tell Click testing to not catch exceptions

---

src/mobu/handlers/external.py

Rather than default arguments, use the Annotated syntax for specifying FastAPI dependencies. This has some advantages, such as relaxing restrictions on the ordering of arguments and unconfusing formatting in some edge cases.

DM-42182: Use new Annotated syntax for handlers

---

Dockerfile
scripts/install-base-packages.sh
scripts/install-dependency-packages.sh

Since we no longer upload intermediate stages, the separation between the dependencies stage and the install stage became irrelevant and they can be combined. Move the installation of Git from the base image to the dependency image, since it's only required during installation.

DM-42182: Simplify the Docker build

---

changelog.d/20231215_141606_rra.md
scripts/install-dependency-packages.sh
src/mobu/exceptions.py
src/mobu/models/business/nublado.py
src/mobu/models/business/nubladopythonloop.py
src/mobu/models/flock.py
src/mobu/models/solitary.py
src/mobu/services/business/notebookrunner.py
src/mobu/services/business/nublado.py
src/mobu/services/business/nubladopythonloop.py
src/mobu/services/monkey.py
src/mobu/storage/nublado.py
tests/autostart_test.py
tests/business/nubladopythonloop_test.py
tests/conftest.py
tests/handlers/solitary_test.py

mobu will not work with an arbitrary JupyterHub; it requires Nublado specifically. Rename JupyterPythonLoop to NubaldoPythonLoop and JupyterClient to NubladoClient to reflect this, although keep the Jupyter naming for things that are more generic to any JupyterHub.

DM-42182: Change some JupyterHub terminology to Nublado

---

changelog.d/20231215_150943_rra_DM_42225.md
src/mobu/asyncio.py
src/mobu/main.py
src/mobu/models/business/base.py
src/mobu/models/business/nublado.py
src/mobu/models/timings.py
src/mobu/services/business/base.py
src/mobu/services/business/nublado.py
src/mobu/services/timings.py
src/mobu/storage/nublado.py
tests/timings_test.py

Use timedelta uniformly internally as the data time for time intervals instead of using an integer number of seconds. Define a serialization format so that the output from the API will stay the same.

DM-42225: Convert intervals to timedeltas

---

.pre-commit-config.yaml
CHANGELOG.md
changelog.d/20231214_124422_rra_DM_42182.md
changelog.d/20231214_165219_rra_DM_42182.md
changelog.d/20231215_141606_rra.md
changelog.d/20231215_143527_rra_DM_42225.md
changelog.d/20231215_150943_rra_DM_42225.md
scripts/install-base-packages.sh
scripts/install-dependency-packages.sh

Restore git to the base image because it's required at runtime.

DM-42225: Prepare 7.0.0 release

---

.github/workflows/periodic.yaml

The periodic CI GitHub Actions configuration was using incorrect syntax for calling into run-neophile. Fix that.

Fix syntax in periodic CI

---

Makefile

The periodic CI job runs make update-deps, so install pre-commit first before running pre-commit autoupdate, rather than assuming make init has already been run.

Install pre-commit before calling autoupdate

---

changelog.d/20240321_110225_rra_DM_43423.md
src/mobu/exceptions.py
src/mobu/storage/nublado.py
tests/support/jupyter.py

Previously, mobu created a fake XSRF cookie and header and sent them blindly to JupyterLab. JupyterLab now expects the cookie to be in a specific format and is rejecting our fake one.
Instead, properly implement the same protocol as the JavaScript client: retrieve the _xsrf cookie from the response from the lab and lift it into the X-XSRFToken header. Raise an exception if the lab does not send an _xsrf cookie so that we'll catch further changes more quickly.
This is complicated by the fact that the hub and lab use separate XSRF tokens restricted to different paths, so we need to track both tokens and send the appropriate header based on which API we're talking to.

DM-43423: Fix XSRF cookie and header handling for JupyterLab

---

changelog.d/20240328_111901_rra_DM_43573.md
src/mobu/storage/nublado.py
tests/support/jupyter.py

httpx does not preserve cookies set by intermediate steps of a redirect chain when following redirects automatically, and the lab sets the XSRF cookie from the oath_callback route and then redirects to the actual lab URL. Disable automatic redirect handling for the lab login and attempt to extract an XSRF cookie at each step.
Also send Sec-Fetch-Mode: navigate to suppress a harmless but annoying logging message in JupyterHub.

DM-43573: Handle cookies from JupyterLab redirects

---

changelog.d/20240719_150741_danfuchs.md
src/mobu/config.py
src/mobu/models/business/notebookrunner.py
src/mobu/services/business/notebookrunner.py
tests/business/notebookrunner_test.py
tests/conftest.py
tests/data/notebooks_services/test-notebook-has-services.ipynb
tests/data/notebooks_services/test-notebook-missing-service.ipynb

* Parse a 'mobu' section out of notebook metadata
* Add a list of available services to app config (to be replaced by some kind of service discovery at some point)
* Don't run the notebook if it declares required services in the metadata and the services aren't available in the environment.
Putting the required services in the notebook metadata can be done in JupyterLab, though is not the nicest UX for this. We now have an in-repo config file (mobu.yaml), maybe it would be better to keep a manifest in there? I like having it closer to the notebook though. I'm open to other suggestions.

DM-45709: Don't run notebooks in environments that don't have the necessary services

---

src/mobu/models/business/notebookrunner.py
src/mobu/services/business/notebookrunner.py
src/mobu/services/github_ci/ci_notebook_job.py
tests/business/notebookrunner_test.py
tests/data/notebooks_services/some-dir/test-other-notebook-has-services.ipynb

GitHub CI checks ask mobu to run an explicit list of notebooks. Some of these notebooks may be excluded once mobu picks up the job though.
This makes sure that these jobs runs the filtered notebooks in a single session.
Mobu could end up not actually running any notebooks, if all of the notebooks in the explicit list are excluded.  In this case, mobu will conclude the check as a success. A future PR will make mobu conclude the check as neutral in this case.

DM-45079: Execute only non-filtered notebooks  when requesting explicit notebooks

---

src/mobu/exceptions.py
src/mobu/services/business/nublado.py

finish business

---

changelog.d/20250131_113522_danfuchs_configurable_concurrency.md
src/mobu/services/manager.py

Remove the limit from the autostart `aiojobs` `Scheduler`. Attempts to start a job past the limit resulted in jobs silently never starting. There are no cases where we would want to limit the autostart concurrency, so a limit is not needed.

DM-48697: No autostart concurrency limit

---

src/mobu/asyncio.py
src/mobu/main.py
src/mobu/services/business/base.py
src/mobu/services/business/notebookrunner.py
src/mobu/services/business/nublado.py
tests/conftest.py

Change the type of functions returning async generators to `AsyncGenerator` and properly close async generators in the hope that this will address various log errors about generators already running.

DM-48825: Properly close async generators

---

src/mobu/config.py
src/mobu/exceptions.py
src/mobu/handlers/external.py
src/mobu/services/monkey.py
tests/conftest.py
tests/data/config/base_no_file_logging.yaml
tests/handlers/flock_test.py

Provides an option to have monkeys log to the global logger instead of a file logger. During scale testing, we may run into ephemeral storage limits when we have so many monkeys writing their logs to files. This lets us just log everything to stdout/err.

DM-48798: Config option to disable monkeys logging to file

---

Dockerfile

Use uv to install Python packages in the Docker image. Add the `--factory` flag to `uvicorn` since the named object is a callable and not an ASGI server object.

DM-48977: Update Dockerfile to use uv

---

changelog.d/20250217_150229_rra_DM_48977.md
src/mobu/asyncio.py
src/mobu/services/business/base.py
src/mobu/services/business/nublado.py
src/mobu/services/business/tap.py

Switch to the new Python syntax for generic parameters to classes and functions. This apparently unconfused mypy and Ruff enough that it uncovered some additional diagnostics, which required some `noqa` comments and some code refactoring, one to fix a bug and another to unconfuse the type checker.

DM-48977: Switch to new Python type variable syntax

---

src/mobu/services/business/base.py
src/mobu/services/business/nublado.py
src/mobu/services/flock.py

Replace calls to `current_datetime(microseconds=True)` with the more native Python library call `datetime.now(tz=UTC)`, which didn't exist when the former was written.

DM-48977: Use datetime.now instead of current_datetime

---

src/mobu/models/business/base.py
src/mobu/models/repo.py

If a Pydantic model uses `model_config` to change the model settings, move that to the top of the class definition instead of the bottom to make it more apparent.

DM-48977: Move model_config to the start of classes

---

src/mobu/config.py
src/mobu/dependencies/config.py
src/mobu/handlers/external.py
src/mobu/handlers/github_ci_app.py
src/mobu/handlers/github_refresh_app.py
src/mobu/handlers/internal.py

Follow our current standard for naming of the global configuration class and rename `Configuration` to `Config`.

DM-48977: Rename Configuration to Config

---

.pre-commit-config.yaml
pyproject.toml

Now that we use Ruff to do most code formatting, remove the Black file ignore configuration. Update the version of Black used for the pre-commit blacken-docs hook.

DM-48977: Remove unneeded Black configuration

---

src/mobu/config.py
src/mobu/factory.py
src/mobu/main.py
src/mobu/services/monkey.py

The Slack alert webhook URL is an incoming webhook that allows direct Slack posting as mobu, so it is a secret and should be treated as such. Change its type in the mobu configuration and pass it directly to the Safir Slack library, since those classes support `SecretStr` as an input type.

DM-48977: Treat the Slack alert webhook as a secret

---

src/monkeyflocker/cli.py

Use the helper function from Safir to display monkeyflocker command line help. Add an `__all__` setting to that file.

DM-48977: Use Safir helper for monkeyflocker help

---

pyproject.toml

The deprecation warning in aiojobs has been fixed, so remove the now-unneeded warning exclusion. Synchronize a few more things with the template `pyproject.toml` to make comparisons easier.

DM-48977: Remove unneeded warning exclusion

---

.github/workflows/ci.yaml
CHANGELOG.md
Makefile
docs/development/sentry.rst
docs/documenteer.toml
docs/index.rst
docs/user_guide/flocks.rst
tox.ini

Add a `docs-linkcheck` tox environment to support the periodic CI run, and fix the link problems that it uncovered. Add a linkcheck action in GitHub Actions, which won't block merging but which will warn if link checking failed.

DM-48977: Add docs-linkcheck target and fix issues

---

src/mobu/services/business/base.py

Use bare `return` instead of a `noaq` marker to indicate that the empty base business methods are intentionally empty and are not missing `abstractmethod` annotations. Thanks to Dan Fuchs for the suggestion.

DM-48977: Avoid noqa markers for empty business methods

---

changelog.d/20250217_173118_danfuchs_DM_48941.md
src/mobu/dependencies/context.py
src/mobu/dependencies/github.py
src/mobu/factory.py
src/mobu/handlers/github_refresh_app.py
src/mobu/models/repo.py
src/mobu/services/business/notebookrunner.py
src/mobu/services/flock.py
src/mobu/services/github_ci/ci_manager.py
src/mobu/services/github_ci/ci_notebook_job.py
src/mobu/services/manager.py
src/mobu/services/monkey.py
src/mobu/services/repo.py
src/mobu/services/solitary.py
tests/business/notebookrunner_test.py
tests/services/ci_manager_test.py
tests/services/repo_cache_test.py

Add a process-global notebook repo cache. Use this in the NotebookRunner business to only clone notebook repos once per process, not once per monkey.
The notebook repo refresh functionality complicates this a bit, see [this comment](https://github.com/lsst-sqre/mobu/pull/407#issue-2854417705)

DM-48941: Only check out notebook repos once

---

changelog.d/20250218_151607_danfuchs_HEAD.md
docs/user-guide/flocks.rst
src/mobu/models/flock.py
src/mobu/services/flock.py
tests/autostart_test.py
tests/services/flock_test.py

Add two new flock config parameters to let us start monkeys in batches with waits in between:
* `start_batch_size`: the number of monkeys to start in each batch
* `start_batch_wait`: the amount of time to wait in between starting batches

DM-49009: Stagered monkey start

---

changelog.d/20250205_175156_steliosvoutsinas_DM_48792.md
src/mobu/data/siaquerysetrunner/dp02/params.yaml
src/mobu/events.py
src/mobu/exceptions.py
src/mobu/models/business/business_config_type.py
src/mobu/models/business/siaquerysetrunner.py
src/mobu/models/monkey.py
src/mobu/services/business/siaquerysetrunner.py
src/mobu/services/monkey.py
tests/business/siaquerysetrunner_test.py

Enables a new QuerySet runner in mobu for SIAv2 Queries. I've defined as range for ra dec & radius and a fixed time which I know should return results when querying the SIAv2 service. We may want to adjust this, but I don't know what options we want to add and this would require some consultation from Tim or a someone more familiar with the datasets and the available images for given query criteria.
This has been defined in a directory `dp02` under `data/siaquerysetrunner`. Reason for not going with dp0.2 is because I re-use this option to generate the URL for the given dataset, because the design of the SIA API is such that it includes the collection, i.e:
`api/sia/dp02/query`
Only some pytests added here, but have not tested on any environment yet.

DM-48792: Create new QuerySet runner for SIAv2

---

src/mobu/services/business/notebookrunner.py
tests/business/notebookrunner_test.py

We're currently recording just the notebook filename in the `notebook` tag on events. We should be recording the entire path relative to the root of the repo.

DM-49241: Record full repo-relative notebook path on events

---

changelog.d/20250305_113624_danfuchs_HEAD.md
src/mobu/config.py
src/mobu/storage/gafaelfawr.py

Add a `gafaelfawr_timeout` config option. With very large numbers of users, like for scale testing, the default httpx timeouts from the [safir http client](https://safir.lsst.io/user-guide/http-client.html) may not be long enough.

DM-49319: Configurable gafaelfawr http client timeout

---

changelog.d/20250307_094752_rra_DM_49374.md
src/mobu/services/flock.py

Batch the creation of Gafaelfawr tokens during flock startup and only perform 10 at a time. This will still provide some parallel speed-up without causing a pile-up on the Gafaelfawr side waiting for database transactions, which in turn causes problems with HTTP timeouts on the mobu side.

DM-49374: Batch Gafaelfawr token creations

---

changelog.d/20250306_142638_danfuchs_HEAD.md
docs/development/idfdev.rst
docs/user-guide/flocks.rst
pyproject.toml
src/mobu/models/business/business_config_type.py
src/mobu/models/business/notebookrunner.py
src/mobu/models/business/notebookrunnercounting.py
src/mobu/models/business/notebookrunnerlist.py
src/mobu/models/flock.py
src/mobu/services/business/notebookrunner.py
src/mobu/services/business/notebookrunnercounting.py
src/mobu/services/business/notebookrunnerlist.py
src/mobu/services/flock.py
src/mobu/services/github_ci/ci_notebook_job.py
src/mobu/services/monkey.py
src/mobu/services/notebook_finder.py
tests/business/notebookrunnercounting_test.py
tests/business/notebookrunnerlist_test.py
tests/handlers/github_refresh_app_test.py
tests/status_test.py

The `NotebookRunner` business currently can accept two kinds of options, one which specifies `max_executions` and runs a constant number of notebooks before refreshing the lab, and one which specifies `notebooks_to_run`, which takes a list of notebooks and runs them all before refreshing.
[To keep consistency with the overall Mobu design](https://github.com/lsst-sqre/mobu/pull/363#discussion_r1688699419), there should be a 1:1 mapping between businesses and business option types. We're about to add a third variation on behavior (don't ever refresh a lab), so by the rule of three, let's clean up this debt and do this refactoring now.
Another piece of debt clean up done here is to split the notebook filtering logic into a helper class.

DM-49320: Refactor notebook businesses

---

CHANGELOG.md

The `NotebookRunnerInfinite` addition was missing a change log entry.

DM-49388: Add missing change log entry for 15.0.0

---

changelog.d/20250317_162821_rra_DM_49526.md
src/mobu/status.py
tests/status_test.py

Stop sending summary messages if there are no flocks running, which will reduce the alert spam on T&S status channels where we currently don't use mobu. The original thought was that this would serve as a sort of heartbeat and would alert us if all flocks were stopped, but we mostly don't manually stop flocks and the annoyance of the empty messages probably exceeds the benefit as a heartbeat.

DM-49526: Skip summary message if there are no flocks
